/**
 * Lucide fallback icons. tastytrade has a real icon library
 * (tastyworks-ui-design-tokens/input/icons/, ~427 icons) but pulling one in
 * ad hoc is slow — see docs/design-foundation.md. Import fallbacks from here
 * (not directly from "lucide-react") so every stand-in icon is easy to find
 * and swap for an official one later: `grep -r "from \"@/lib/icons\""`.
 */
export {
  Activity,
  AlertTriangle,
  ArrowDownRight,
  ArrowLeftRight,
  ArrowRight,
  ArrowUpRight,
  Award,
  BatteryFull,
  Bell,
  Bitcoin,
  Check,
  ChevronDown,
  ChevronRight,
  Coffee,
  Compass,
  Cpu,
  ExternalLink,
  Eye,
  EyeOff,
  Flame,
  HeartPulse,
  Home,
  Landmark,
  Lightbulb,
  LineChart,
  Lock,
  MessageCircle,
  Minus,
  Newspaper,
  Pencil,
  Plane,
  Plus,
  RotateCcw,
  Search,
  Settings,
  Shield,
  ShoppingBag,
  Signal,
  Sparkles,
  TrendingDown,
  TrendingUp,
  Tv,
  Unlock,
  User,
  Wallet,
  Wifi,
  X,
  Zap,
} from "lucide-react"
